[features]
seeds = false
skip-lint = false
[programs.localnet]
movie_review_program_pda = "EK9L2wcNcyTyymvBcdNsk7QDq1JF9Q7DS9763FAjdFrZ"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "Localnet"
wallet = "/Users/sandeep/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
