[features]
seeds = false
skip-lint = false
[programs.localnet]
movie_review_program_cpi = "AsE144X8Zp3YVFS8umdqHFfyUNLQosQ7mnCFEG2x1aTB"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "Localnet"
wallet = "/Users/sandeep/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
